GET http://localhost:3000/pilots/availability?location=Munich&depDateTime=2025-08-01T00:00:00Z&returnDateTime=2025-08-02T00:00:00Z

###

POST http://localhost:3000/flights
Content-Type: application/json

{
    "pilotId": 4,
    "depDateTime": "2025-08-01T09:00:00Z",
    "returnDateTime": "2025-08-01T10:00:00Z"
}